=== stairman06/omf/schema/instance.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "required": [
        "formatType",
        "formatVersion"
    ],
    "properties": {
        "formatType": {
            "const": "instance"
        },
        "formatVersion": {
            "const": 0
        },
        "project": {
            "$ref": "meta.schema.json#/definitions/projectMeta"
        },
        "version": {
            "$ref": "meta.schema.json#/definitions/versionMeta"
        },
        "assets": {
            "type": "array",
            "items": {
                "type": "object",
                "required": [
                    "id",
                    "type",
                    "env",
                    "file"
                ],
                "properties": {
                    "id": {
                        "type": "string"
                    },
                    "type": {
                        "enum": [
                            "local",
                            "remote"
                        ]
                    },
                    "env": {
                        "$ref": "meta.schema.json#/definitions/env"
                    },
                    "file": {
                        "$ref": "meta.schema.json#/definitions/fileMeta"
                    },
                    "groups": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    }
                },
                "oneOf": [
                    {
                        "properties": {
                            "type": {
                                "const": "local"
                            }
                        }
                    },
                    {
                        "properties": {
                            "type": {
                                "const": "remote"
                            },
                            "file": {
                                "required": [
                                    "downloads",
                                    "hashes",
                                    "size"
                                ]
                            }
                        }
                    }
                ]
            }
        },
        "groups": {
            "type": "object",
            "additionalProperties": {
                "type": "object",
                "required": [
                    "name"
                ],
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "description": {
                        "type": "string"
                    },
                    "overrides": {
                        "type": "string"
                    },
                    "env": {
                        "$ref": "meta.schema.json#/definitions/env"
                    },
                    "conflicts": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "requires": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "components": {
            "type": "object",
            "description": "Required components for the Pack",
            "required": [
                "minecraft"
            ],
            "properties": {
                "minecraft": {
                    "description": "Version of Minecraft"
                },
                "forge": {
                    "description": "Version of Minecraft Forge"
                },
                "fabric-loader": {
                    "description": "Version of Fabric Loader"
                },
                "quilt-loader": {
                    "description": "Version of Quilt Loader"
                }
            }
        },
        "config": {
            "type": "object",
            "properties": {
                "ram": {
                    "type": "object",
                    "properties": {
                        "min": {
                            "type": "number",
                            "description": "Minimum number of gigabytes of RAM required (inclusive)"
                        },
                        "max": {
                            "type": "number",
                            "description": "Maximum number of gigabytes of RAM required (inclusive)"
                        }
                    }
                },
                "java": {
                    "type": "object",
                    "properties": {
                        "min": {
                            "type": "integer",
                            "description": "Minimum Java version allowed (inclusive)"
                        },
                        "max": {
                            "type": "integer",
                            "description": "Maximum Java version allowed (inclusive)"
                        }
                    }
                }
            }
        }
    }
}

=== stairman06/omf/examples/example-pack/instance.omf.json
{
    "$schema": "../../schema/instance.schema.json",
    "formatType": "instance",
    "formatVersion": 0,
    "project": {
        "id": "com.example.Modpack",
        "src": "https://api.example.com/omf/example-pack.omf.json",
        "name": "Example modpack"
    },
    "version": {
        "id": "1.0.0",
        "src": "https://api.example.com/omf/example-pack/1.0.omf.json",
        "name": "Release 1.0"
    },
    "assets": [
        {
            "id": "my-custom-loader",
            "type": "remote",
            "env": {
                "client": "required",
                "server": "disallowed"
            },
            "file": {
                "type": "versionJson",
                "downloads": [
                    "https://example.com/myloader.json"
                ],
                "hashes": {
                    "sha512": "< sum >"
                },
                "size": 1
            }
        },
        {
            "id": "myjarmod",
            "type": "local",
            "env": {
                "client": "required",
                "server": "required"
            },
            "file": {
                "type": "jarmod",
                "size": 1
            }
        },
        {
            "id": "mymod",
            "type": "remote",
            "env": {
                "client": "required",
                "server": "disallowed"
            },
            "file": {
                "type": "raw",
                "dest": "mods/mymod.jar",
                "downloads": [
                    "https://example.com/mymod.jar"
                ],
                "hashes": {
                    "sha1": "< sum >"
                },
                "size": 1
            },
            "groups": [
                "group-three"
            ],
            "project": {
                "id": "com.example.MyMod",
                "src": "https://api.example.com/omf/mymod.omf.json",
                "name": "My Mod",
                "x-fabric": {
                    "modid": "mymod"
                },
                "x-modrinth": {
                    "id": "ABC123"
                }
            },
            "version": {
                "id": "1.0",
                "src": "https://api.example.com/omf/mymod/1.0.omf.json",
                "name": "Release 1.0",
                "x-modrinth": {
                    "id": "XYZ789"
                }
            }
        }
    ],
    "groups": {
        "group-one": {
            "name": "Group 1",
            "description": "This is an example group",
            "conflicts": [
                "group-two"
            ],
            "requires": [
                "group-three"
            ]
        },
        "group-two": {
            "name": "Group 2",
            "conflicts": [
                "group-one"
            ]
        },
        "group-three": {
            "name": "Group 3",
            "overrides": "my-conditional",
            "env": {
                "client": "required",
                "server": "disallowed"
            }
        }
    },
    "components": {
        "minecraft": "1.18.2",
        "fabric-loader": "0.10.2"
    },
    "config": {
        "ram": {
            "min": 2,
            "max": 3
        },
        "java": {
            "min": 8
        }
    }
}
