=== stairman06/omf/schema/pack.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "required": [
        "formatType",
        "formatVersion"
    ],
    "definitions": {
        "env": {
            "type": "object",
            "description": "Environment where this can be used",
            "required": [
                "client",
                "server"
            ],
            "properties": {
                "client": {
                    "description": "Client side",
                    "$ref": "#/definitions/envValue"
                },
                "server": {
                    "description": "Server side",
                    "$ref": "#/definitions/envValue"
                }
            }
        },
        "envValue": {
            "enum": [
                "required",
                "optional",
                "disallowed"
            ]
        }
    },
    "properties": {
        "formatType": {
            "const": "omf:pack"
        },
        "formatVersion": {
            "const": 0
        },
        "components": {
            "type": "object",
            "description": "Required components for the Pack",
            "required": [
                "minecraft"
            ],
            "properties": {
                "minecraft": {
                    "description": "Version of Minecraft"
                },
                "forge": {
                    "description": "Version of Minecraft Forge"
                },
                "fabric-loader": {
                    "description": "Version of Fabric Loader"
                },
                "quilt-loader": {
                    "description": "Version of Quilt Loader"
                }
            }
        },
        "files": {
            "type": "array",
            "items": {
                "type": "object",
                "required": [
                    "fileType",
                    "id",
                    "hashes",
                    "fileSize"
                ],
                "properties": {
                    "id": {
                        "type": "string"
                    },
                    "downloads": {
                        "type": "array",
                        "items": {
                            "type": "string",
                            "format": "uri"
                        },
                        "minItems": 1
                    },
                    "local": {
                        "type": "string"
                    },
                    "hashes": {
                        "$ref": "meta.schema.json#/definitions/hashes"
                    },
                    "fileSize": {
                        "$ref": "meta.schema.json#/definitions/fileSize"
                    },
                    "env": {
                        "$ref": "#/definitions/env"
                    },
                    "groups": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "meta": {
                        "$ref": "meta.schema.json#/definitions/combinedMeta"
                    }
                },
                "anyOf": [
                    {
                        "required": [
                            "downloads"
                        ]
                    },
                    {
                        "required": [
                            "local"
                        ]
                    }
                ],
                "oneOf": [
                    {
                        "properties": {
                            "fileType": {
                                "const": "versionJson"
                            }
                        }
                    },
                    {
                        "properties": {
                            "fileType": {
                                "const": "jarmod"
                            }
                        }
                    },
                    {
                        "required": [
                            "path"
                        ],
                        "properties": {
                            "fileType": {
                                "const": "raw"
                            },
                            "path": {
                                "type": "string"
                            }
                        }
                    }
                ]
            }
        },
        "groups": {
            "type": "object",
            "additionalProperties": {
                "type": "object",
                "required": [
                    "name"
                ],
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "description": {
                        "type": "string"
                    },
                    "overrides": {
                        "type": "string"
                    },
                    "env": {
                        "$ref": "#/definitions/env"
                    },
                    "conflicts": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "requires": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "meta": {
            "$ref": "meta.schema.json#/definitions/combinedMeta"
        },
        "config": {
            "type": "object",
            "properties": {
                "ram": {
                    "type": "object",
                    "properties": {
                        "min": {
                            "type": "number",
                            "description": "Minimum number of gigabytes of RAM required (inclusive)"
                        },
                        "max": {
                            "type": "number",
                            "description": "Maximum number of gigabytes of RAM required (inclusive)"
                        }
                    }
                },
                "java": {
                    "type": "object",
                    "properties": {
                        "min": {
                            "type": "integer",
                            "description": "Minimum Java version allowed (inclusive)"
                        },
                        "max": {
                            "type": "integer",
                            "description": "Maximum Java version allowed (inclusive)"
                        }
                    }
                }
            }
        }
    }
}

=== stairman06/omf/examples/example-pack/index.omf.json
{
    "$schema": "../../schema/pack.schema.json",
    "formatType": "omf:pack",
    "formatVersion": 0,
    "meta": {
        "omf:project.src": "https://api.example.com/omf/example-pack.omf.json",
        "omf:version.src": "https://api.example.com/omf/example-pack/1.0.omf.json",
        "omf:project.name": "Example modpack",
        "omf:version.name": "Release 1.0 for Minecraft 1.18",
        "omf:version.id": "1"
    },
    "components": {
        "minecraft": "1.18.2",
        "fabric-loader": "0.10.2"
    },
    "files": [
        {
            "fileType": "versionJson",
            "id": "my-custom-loader",
            "downloads": [
                "https://example.com/my-custom-loader.json"
            ],
            "local": "my-custom-loader.json",
            "hashes": {
                "sha512": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            },
            "fileSize": 1
        },
        {
            "fileType": "jarmod",
            "id": "myjarmod",
            "downloads": [
                "https://example.com/myjarmod.zip"
            ],
            "hashes": {
                "sha1": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            },
            "fileSize": 1
        },
        {
            "fileType": "raw",
            "id": "mymod",
            "path": "mods/mymod.jar",
            "downloads": [
                "https://example.com/mymod.jar"
            ],
            "hashes": {
                "sha1": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            },
            "fileSize": 123,
            "groups": [
                "group-three"
            ],
            "env": {
                "client": "optional",
                "server": "disallowed"
            },
            "meta": {
                "omf:project.src": "https://api.example.com/omf/mymod.omf.json",
                "omf:version.src": "https://api.example.com/omf/mymod/1.0.omf.json",
                "omf:project.name": "My Mod",
                "omf:version.id": "1.0",
                "omf:version.name": "My Version",
                "fabric-loader:modid": "mymod",
                "modrinth:id": "ABC123",
                "modrinth:version": "XYZ789"
            }
        }
    ],
    "groups": {
        "group-one": {
            "name": "Group 1",
            "description": "This is an example group",
            "conflicts": [
                "group-two"
            ],
            "requires": [
                "group-three"
            ]
        },
        "group-two": {
            "name": "Group 2",
            "conflicts": [
                "group-one"
            ]
        },
        "group-three": {
            "name": "Group 3",
            "overrides": "my-conditional-overrides",
            "env": {
                "client": "required",
                "server": "disallowed"
            }
        }
    },
    "config": {
        "ram": {
            "min": 2,
            "max": 3
        },
        "java": {
            "min": 8
        }
    }
}
