=== stairman06/omf/schema/version.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "required": [
        "formatType",
        "formatVersion"
    ],
    "properties": {
        "formatType": {
            "const": "omf:version"
        },
        "formatVersion": {
            "const": 0
        },
        "meta": {
            "$ref": "meta.schema.json#/definitions/combinedMeta"
        },
        "files": {
            "type": "array",
            "description": "Files in this Version",
            "items": {
                "type": "object",
                "required": [
                    "fileType",
                    "downloads",
                    "hashes",
                    "fileSize"
                ],
                "properties": {
                    "primary": {
                        "type": "boolean"
                    },
                    "downloads": {
                        "type": "array",
                        "description": "URLs where this file can be downloaded",
                        "items": {
                            "type": "string",
                            "format": "uri"
                        },
                        "minItems": 1
                    },
                    "hashes": {
                        "$ref": "meta.schema.json#/definitions/hashes"
                    },
                    "fileSize": {
                        "$ref": "meta.schema.json#/definitions/fileSize"
                    }
                },
                "oneOf": [
                    {
                        "properties": {
                            "fileType": {
                                "const": "raw"
                            },
                            "fileName": {
                                "type": "string",
                                "description": "Name of this file"
                            }
                        }
                    },
                    {
                        "properties": {
                            "fileType": {
                                "const": "jarmod"
                            }
                        }
                    },
                    {
                        "properties": {
                            "fileType": {
                                "const": "versionJson"
                            }
                        }
                    },
                    {
                        "properties": {
                            "fileType": {
                                "const": "omfPack"
                            }
                        }
                    }
                ]
            }
        }
    }
}

=== stairman06/omf/examples/example-pack-meta/1.0.omf.json
{
    "$schema": "../../schema/version.schema.json",
    "formatType": "omf:version",
    "formatVersion": 0,
    "meta": {
        "omf:project.src": "https://api.example.com/omf/example-pack.omf.json",
        "omf:project.name": "Example modpack",
        "omf:version.id": "1.0",
        "omf:version.name": "test",
        "omf:version.components": {
            "minecraft": "1.18.2",
            "fabric-loader": "0.10.2"
        },
        "omf:version.dependencies": {
            "example-mod": {
                "type": "required",
                "meta": {
                    "omf:project.src": "https://api.example.com/omf/example-mod.omf.json"
                }
            }
        }
    },
    "files": [
        {
            "primary": true,
            "fileType": "omfPack",
            "downloads": [
                "https://cdn.example.com/omf/example-pack.omfpack"
            ],
            "hashes": {
                "sha1": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            },
            "fileSize": 1234
        }
    ]
}

=== stairman06/omf/examples/example-mod-meta/1.0.omf.json
{
    "$schema": "../../schema/version.schema.json",
    "formatType": "omf:version",
    "formatVersion": 0,
    "meta": {
        "omf:project.src": "https://api.example.com/omf/example-mod.omf.json",
        "omf:project.type": "mod",
        "omf:version.id": "1.0",
        "omf:version.name": "test",
        "omf:version.components": {
            "minecraft": "1.18.2",
            "fabric-loader": "0.10.2"
        },
        "omf:version.dependencies": {
            "fabric-api": {
                "type": "required"
            }
        },
        "omf:version.changelog": "Added new features"
    },
    "files": [
        {
            "primary": true,
            "fileType": "raw",
            "fileName": "example-mod.jar",
            "downloads": [
                "https://cdn.example.com/omf/example-mod.jar"
            ],
            "hashes": {
                "sha512": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
            },
            "fileSize": 12345
        }
    ]
}
